development:
  sessions:
    default:
      database: plv_hq_dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: plv_hq_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0

production:
  sessions:
    default:
      database: plv_hq
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0

